# Generated by Django 4.1.5 on 2023-01-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='archive',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='reciever',
            new_name='recipients',
        ),
    ]
