# Generated by Django 4.1.5 on 2023-09-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_rename_archive_email_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='parent_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mail.email'),
        ),
        migrations.AddField(
            model_name='email',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_thread', to='mail.email'),
        ),
    ]
