# Generated by Django 4.1.5 on 2023-09-20 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_email_parent_email_email_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='mail.email'),
        ),
    ]
