# Generated by Django 4.1.5 on 2023-09-21 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_email_forwarded_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.ManyToManyField(blank=True, null=True, related_name='bccd', to=settings.AUTH_USER_MODEL),
        ),
    ]
