# Generated by Django 4.1.5 on 2023-09-23 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_email_bcc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('body', models.TextField(blank=True)),
                ('scheduled_datetime', models.DateTimeField()),
                ('bcc', models.ManyToManyField(blank=True, null=True, related_name='bccd_to_be_emails', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='emails_to_be_recieved', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_to_be_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
