# Generated by Django 4.1.5 on 2023-09-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_schedledemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchedledEmail',
            new_name='ScheduledEmail',
        ),
    ]
