# Generated by Django 4.1.5 on 2023-09-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachements/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='attachement_thumbnails/')),
            ],
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.AddField(
            model_name='email',
            name='attachment',
            field=models.ManyToManyField(related_name='attached_to', to='mail.uploadedfile'),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='attachment',
            field=models.ManyToManyField(related_name='attachments_to', to='mail.uploadedfile'),
        ),
    ]
