# Generated by Django 4.1.5 on 2023-09-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_uploadedfile_delete_attachment_email_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
