# Generated by Django 4.1.5 on 2023-09-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_alter_uploadedfile_file_alter_uploadedfile_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='attachment',
            new_name='attachments',
        ),
        migrations.RenameField(
            model_name='scheduledemail',
            old_name='attachment',
            new_name='attachments',
        ),
    ]
